src/libs/config.js, src/scenes/trips/components/edit_trip_component.jsx, src/scenes/trips/containers/edit_trip_container.js, src/scenes/trips/containers/trips_container.js, src/scenes/trips/trips.js, src/shared_components/Carts/Location.js, src/shared_components/Nav/DesktopDropDownMenu.js, src/styled_scenes/Account/Trips/shared/Carts/Location.js, src/styled_scenes/Account/Trips/shared/TripSectionComponent.js, src/styled_scenes/EditTrip/components/ChangeTripImageButton.js, src/styled_scenes/EditTrip/components/Day.js, src/styled_scenes/EditTrip/components/EmptyTripDay.js, src/styled_scenes/EditTrip/components/MobileFilter.js, src/styled_scenes/EditTrip/components/Results.js, src/styled_scenes/EditTrip/components/ShareButton.js, src/styled_scenes/EditTrip/components/ShareDialogContent.js, src/styled_scenes/EditTrip/components/Summary.js, src/styled_scenes/EditTrip/components/ToolBar/NonOwnerToolBar.js, src/styled_scenes/EditTrip/components/ToolBar/OwnerToolBar.js, src/styled_scenes/EditTrip/components/ToolBar/ResponsiveToolBarWrap.js, src/styled_scenes/EditTrip/components/ToolBar/ToolBar.js, src/styled_scenes/EditTrip/components/ToolBar/ToolbarButton.js, src/styled_scenes/EditTrip/components/ToolBar/index.js, src/styled_scenes/EditTrip/components/ToolBar/toolbar-proptypes.js, src/styled_scenes/EditTrip/components/styles.js, src/styled_scenes/EditTrip/index.js, src/styled_scenes/Results/components/Results.js, src/styled_scenes/Results/index.js, src/styled_scenes/Trips/index.js
That will be an ongoing story to refactor Trips page....
=> Edit trip page

.circleci/config.yml
Small updates for deployment, this we change the commit status rather than commenting the PR.
Commit pushed:
Finished (all checks passed):
=> Improve acceptance tests

.circleci/config.yml
This will link to a static `now.sh` URL, e.g. `https://please-<branch-name>.now.sh`
The URL for this particular PR is: https://please-alias-branch-name-to-nowsh.now.sh/
=> Alias branch name to now.sh

.circleci/config.yml, README.md, src/scenes/trips/containers/edit_trip_container.js
Displays 404 page if user is not trip owner.
=> restricting edit trip page access to trip owner

src/libs/Utils.js, src/scenes/account/components/account_trips_all_component.jsx, src/styled_scenes/Service/components/AddToTripButton/TripsListInDropDown.js, src/styled_scenes/Service/components/AddToTripButton/index.js, src/styled_scenes/Trips/components/Summary.js
This will replace text, fix linter issue, and small cleanup around that linting issue.
=> Change button name, clean up sorting

src/shared_components/Carts/Location.js
- Add links to trip cards on the Service page
- Remove some duplication
Ticket: https://www.pivotaltracker.com/story/show/159302048
=> refactor + linkify trip cards

src/scenes/trips/actions.js, src/scenes/trips/containers/EditTripContainer.js, src/scenes/trips/containers/ViewTripContainer.js, src/scenes/trips/reducers.js, src/styled_scenes/EditTrip/components/AddNewServiceToTrip.js, src/styled_scenes/EditTrip/components/ToolBar/EditTripForm.js
Fixes: https://sentry.io/share/issue/cde65338c9e645f2a6ce5843d1e3ea16/
=> #159391456 fix bug where trip data was reset after component mounted

src/scenes/trips/actions.js, src/scenes/trips/reducers.js, src/styled_scenes/EditTrip/components/AddNotesButton.js, src/styled_scenes/EditTrip/components/ModifiableDayList.js
Ticket: https://www.pivotaltracker.com/story/show/159390907
=> Add notes button #159390907

src/styled_scenes/EditTrip/components/ToolBar/EditTripForm.js, src/styled_scenes/EditTrip/components/ToolBar/TripLengthFormInput.js
Ticket: https://www.pivotaltracker.com/story/show/159391356
=> #159391356 Edit trip start date

src/styled_scenes/EditTrip/components/ToolBar/EditTripForm.js
- edit trip form is validated on `componentDidMount`
- minor text change
=> validate edit trip form on mount

src/styled_scenes/Account/Trips/All/index.js, src/styled_scenes/Account/Trips/Completed/index.js, src/styled_scenes/Account/Trips/Planned/index.js, src/styled_scenes/Account/Trips/shared/TripSectionComponent.js
Show a message if there are no trips on user profile ...
=> Show a message if there are no trips on user profile

src/shared_components/Carts/DetailCart/FullCart.js, src/shared_components/Carts/DetailCart/components/CopyServiceToDayButton.js, src/shared_components/Carts/DetailCart/components/icons.js
Ticket: https://www.pivotaltracker.com/story/show/159060522
=> #159060522 Add support for Multi day services

src/index.js, src/styled_scenes/EditTrip/index.js
Story: https://www.pivotaltracker.com/story/show/159398237
This PR will remove add new service button from edit trip view.
@vlddlv I was not able to mark this started in Pivotal as requested, I don't think I have the correct permissions.
=> 159398237 remove new service button

src/data/nav.js, src/libs/feature-flags.js, src/scenes/checkout/CheckoutContainer.js, src/scenes/checkout/CheckoutTripContainer.js, src/scenes/checkout/PaymentContainer.js, src/scenes/checkout/actions.js, src/scenes/checkout/components/CheckoutTrip.js, src/scenes/checkout/components/PaymentSection/index.js, src/scenes/checkout/components/TripDay/index.js, src/scenes/trips/actions.js, src/scenes/trips/reducers.js, src/scenes/trips/selectors.js, src/shared_components/Carts/DetailCart/ExcerptCart.js, src/shared_components/Carts/DetailCart/components/Category.js, src/shared_components/Carts/DetailCart/components/Description.js
Extra changes apart from ticket #160196145
=> Checkout with the new Serverless API #160196145

public/index.html, src/scenes/home/containers/home_container.js
This PR removes the yellow teaser that indicates demo.
=> remove banner

src/libs/categories.js, src/libs/fetch_helpers.js, src/scenes/trip/actions.js, src/shared_components/icons/index.js, src/styled_scenes/Trip/DaySelector.js, src/styled_scenes/Trip/FixedFooter.js, src/styled_scenes/Trip/Itinerary.js, src/styled_scenes/Trip/TripDescription.js, src/styled_scenes/Trip/index.js
The mobile design is almost ready, but I think we can merge it as it is, it's really an improvement in design (even in desktop).
I go on with trip organizer as we said in the daily.
=> #160791182 View trip mobile design

src/libs/Utils.js, src/main/app.js, src/scenes/checkout/components/CheckoutTrip.js, src/scenes/trip-share/containers/TripShare.js, src/scenes/trip-share/index.js, src/scenes/trip/actions.js, src/scenes/trip/containers/TripContainer.js, src/shared_components/Button/index.js, src/shared_components/Cards/Trip.js, src/shared_components/Category.js, src/shared_components/Form/SemanticLocationControl.js, src/shared_components/Nav/MobileDropdownMenu.js, src/shared_components/StyledInput.js, src/shared_components/layout/Page.js, src/styled_scenes/Trip/DaySelector.js, src/styled_scenes/Trip/Itinerary.js, src/styled_scenes/Trip/index.js, src/styled_scenes/Trip/mapServicesToDays.js, src/styled_scenes/TripOrganizer/AddServiceModal.js, src/styled_scenes/TripOrganizer/CheckoutBox.js, src/styled_scenes/TripOrganizer/Itinerary.js, src/styled_scenes/TripOrganizer/Options.js, src/styled_scenes/TripOrganizer/index.js, src/styled_scenes/TripOrganizer/styles.css, src/styled_scenes/TripShare/index.js
Please don't merge until tested in this branch.
=> 160482625 trip organizer design

src/scenes/results/actions.js, src/scenes/results/containers/results_container.js, src/scenes/results/results.js, src/styled_scenes/Results/components/Filters.js
I had to handle some stuff different because we don't want to request in each change, you might want to check it @dm0lz
=> #161269822 Add radius to search

src/shared_components/MapMarker/index.js, src/styled_scenes/Results/index.js
Add a label to markers on hover so its possible to see what location is where.
closing #288 
**Preview of marker**
=> Add labels to map markers

src/scenes/registrations/actions.js, src/scenes/registrations/components/registrations_component.jsx, src/scenes/registrations/containers/registrations_container.js, src/scenes/registrations/reducers.js
Add loader on Register click #251
=> Add loader on Register click #251

src/scenes/sessions/actions.js, src/scenes/sessions/components/login_form_component.jsx, src/scenes/sessions/containers/sessions_container.js, src/scenes/sessions/reducers.js
Creates an action creator and a loading flag on reducer to display the loading prop when the button is clicked. Happy Hacktoberfest!!
=> Add Loader on Login click #250

src/shared_components/Cards/Trip.js
- Move popup close to the title (instead of being on top of the card)
=> Improve truncated title popup

src/main/app.js, src/main/middlewares/ScrollToTop.js
Reverts PleaseDotCom/frontend#287
=> Revert "Remove scrollToTop middleware"

src/scenes/services/actions.js
when sending the payload for a new trip
=> make sure we send only serviceId in services[].service

src/scenes/registrations/actions.js, src/scenes/sessions/actions.js
To be merged only after running the script to update all prod users email_verified to true.
=> user must verify email before login

src/styled_scenes/TripOrganizer/index.js
I struggled to fix this because of the issues in staging.
=> #162663092 Fix day removal bug

src/libs/location.js, src/scenes/results/containers/results_container.js, src/scenes/results/results.js, src/shared_components/TopBar/Search/Search.js, src/store/search/actions.js, src/styled_scenes/Home/components/HomeSearch.js
=> Search params tweaking 164084432
